//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservoForm.Client.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObservoForm.Client.Common.Resources.ResStrings", typeof(ResStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Ttl {
            get {
                return ResourceManager.GetString("About_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more....
        /// </summary>
        internal static string AddMore_Btn {
            get {
                return ResourceManager.GetString("AddMore_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New observation.
        /// </summary>
        internal static string AddObservation_BtnBar {
            get {
                return ResourceManager.GetString("AddObservation_BtnBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Observo is available in the store. Please update your version..
        /// </summary>
        internal static string AppUpdateRequired_Msg {
            get {
                return ResourceManager.GetString("AppUpdateRequired_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        internal static string AppUpdateRequired_Ttl {
            get {
                return ResourceManager.GetString("AppUpdateRequired_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back_Btn {
            get {
                return ResourceManager.GetString("Back_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reference point.
        /// </summary>
        internal static string Bezugspunkt_Lbl {
            get {
                return ResourceManager.GetString("Bezugspunkt_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tap on tick once the {0}&quot; reference point is correctly located.Tap on Back button to avoid the placement..
        /// </summary>
        internal static string BezugspunktPlacementHint_Lbl {
            get {
                return ResourceManager.GetString("BezugspunktPlacementHint_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_Btn {
            get {
                return ResourceManager.GetString("Cancel_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates....
        /// </summary>
        internal static string CheckUpdates_Btn {
            get {
                return ResourceManager.GetString("CheckUpdates_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an action....
        /// </summary>
        internal static string ChooseAction_DialTtl {
            get {
                return ResourceManager.GetString("ChooseAction_DialTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of the form you want to create:.
        /// </summary>
        internal static string ChooseNewObservationType_Lbl {
            get {
                return ResourceManager.GetString("ChooseNewObservationType_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New observation....
        /// </summary>
        internal static string ChooseNewObservationType_Ttl {
            get {
                return ResourceManager.GetString("ChooseNewObservationType_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon....
        /// </summary>
        internal static string ComingSoon_Lbl {
            get {
                return ResourceManager.GetString("ComingSoon_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication problem.
        /// </summary>
        internal static string CommunicationProblem_Ttl {
            get {
                return ResourceManager.GetString("CommunicationProblem_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraiton.
        /// </summary>
        internal static string Configuration_Ttl {
            get {
                return ResourceManager.GetString("Configuration_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ConfirmDelete_Ttl {
            get {
                return ResourceManager.GetString("ConfirmDelete_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the current reference point?.
        /// </summary>
        internal static string ConfirmDeleteBp_Msg {
            get {
                return ResourceManager.GetString("ConfirmDeleteBp_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the photo?.
        /// </summary>
        internal static string ConfirmDeletePhoto_Msg {
            get {
                return ResourceManager.GetString("ConfirmDeletePhoto_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the voice record?.
        /// </summary>
        internal static string ConfirmDeleteVoice_Msg {
            get {
                return ResourceManager.GetString("ConfirmDeleteVoice_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactPage_Ttl {
            get {
                return ResourceManager.GetString("ContactPage_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        internal static string Coordinates_Lbl {
            get {
                return ResourceManager.GetString("Coordinates_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_Btn {
            get {
                return ResourceManager.GetString("Delete_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the observation form.
        /// </summary>
        internal static string DeleteForm_Ttl {
            get {
                return ResourceManager.GetString("DeleteForm_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the observation?.
        /// </summary>
        internal static string DeleteObservation_Msg {
            get {
                return ResourceManager.GetString("DeleteObservation_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the package data?.
        /// </summary>
        internal static string DeletePackageData_Msg {
            get {
                return ResourceManager.GetString("DeletePackageData_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device identifier.
        /// </summary>
        internal static string DeviceIdentifier_Lbl {
            get {
                return ResourceManager.GetString("DeviceIdentifier_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on the map.
        /// </summary>
        internal static string DisplayOnMap_Btn {
            get {
                return ResourceManager.GetString("DisplayOnMap_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download_Btn {
            get {
                return ResourceManager.GetString("Download_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string East_Lbl {
            get {
                return ResourceManager.GetString("East_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail address.
        /// </summary>
        internal static string EmailRequired_Msg {
            get {
                return ResourceManager.GetString("EmailRequired_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format. Please enter a valid email address..
        /// </summary>
        internal static string EmailWrongFormat_Msg {
            get {
                return ResourceManager.GetString("EmailWrongFormat_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tap to enter your text....
        /// </summary>
        internal static string EnterFreeText_Lbl {
            get {
                return ResourceManager.GetString("EnterFreeText_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text....
        /// </summary>
        internal static string FreeText_Lbl {
            get {
                return ResourceManager.GetString("FreeText_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the server. Please retry a few minutes later..
        /// </summary>
        internal static string HostNotReachable_Msg {
            get {
                return ResourceManager.GetString("HostNotReachable_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import_Btn {
            get {
                return ResourceManager.GetString("Import_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ImportDone {
            get {
                return ResourceManager.GetString("ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building miniatures.
        /// </summary>
        internal static string ImportPackageStatus_BuildingMiniatures {
            get {
                return ResourceManager.GetString("ImportPackageStatus_BuildingMiniatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building miniatures failed.
        /// </summary>
        internal static string ImportPackageStatus_BuildingMiniaturesFailed {
            get {
                return ResourceManager.GetString("ImportPackageStatus_BuildingMiniaturesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data failed.
        /// </summary>
        internal static string ImportPackageStatus_DownloadDataFailed {
            get {
                return ResourceManager.GetString("ImportPackageStatus_DownloadDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package data.
        /// </summary>
        internal static string ImportPackageStatus_DownloadingData {
            get {
                return ResourceManager.GetString("ImportPackageStatus_DownloadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package media files.
        /// </summary>
        internal static string ImportPackageStatus_DownloadingMedia {
            get {
                return ResourceManager.GetString("ImportPackageStatus_DownloadingMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading media failed.
        /// </summary>
        internal static string ImportPackageStatus_DownloadMediaFailed {
            get {
                return ResourceManager.GetString("ImportPackageStatus_DownloadMediaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import package failed.
        /// </summary>
        internal static string ImportPackageStatus_ImportDataFailed {
            get {
                return ResourceManager.GetString("ImportPackageStatus_ImportDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing package data.
        /// </summary>
        internal static string ImportPackageStatus_ImportingData {
            get {
                return ResourceManager.GetString("ImportPackageStatus_ImportingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available on server.
        /// </summary>
        internal static string ImportPackageStatus_NewVersionAvailable {
            get {
                return ResourceManager.GetString("ImportPackageStatus_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for download.
        /// </summary>
        internal static string ImportPackageStatus_ReadyForDownload {
            get {
                return ResourceManager.GetString("ImportPackageStatus_ReadyForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping media failed.
        /// </summary>
        internal static string ImportPackageStatus_UnzipMediaFailed {
            get {
                return ResourceManager.GetString("ImportPackageStatus_UnzipMediaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping package media files.
        /// </summary>
        internal static string ImportPackageStatus_UnzippingMedia {
            get {
                return ResourceManager.GetString("ImportPackageStatus_UnzippingMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package is up to date.
        /// </summary>
        internal static string ImportPackageStatus_UpToDate {
            get {
                return ResourceManager.GetString("ImportPackageStatus_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package import has been stuck. Please restart it..
        /// </summary>
        internal static string ImportPackageStuck_Lbl {
            get {
                return ResourceManager.GetString("ImportPackageStuck_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data starting.
        /// </summary>
        internal static string ImportStarting {
            get {
                return ResourceManager.GetString("ImportStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfuly done:
        ///- {0} new objects imported
        ///- {1} objects updated
        ///- {2} objects unchanged.
        /// </summary>
        internal static string ImportSummaryMsg {
            get {
                return ResourceManager.GetString("ImportSummaryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ImportSummaryTitle {
            get {
                return ResourceManager.GetString("ImportSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later_Btn {
            get {
                return ResourceManager.GetString("Later_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal informations.
        /// </summary>
        internal static string LegalInformations {
            get {
                return ResourceManager.GetString("LegalInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence request has been successfully submitted and will be processed as soon as possible..
        /// </summary>
        internal static string LicenceRequestSentMsg {
            get {
                return ResourceManager.GetString("LicenceRequestSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence request.
        /// </summary>
        internal static string LicenceRequestSentTitle {
            get {
                return ResourceManager.GetString("LicenceRequestSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainMenu_Ttl {
            get {
                return ResourceManager.GetString("MainMenu_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandant {0}.
        /// </summary>
        internal static string MandantName_Ttl {
            get {
                return ResourceManager.GetString("MandantName_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandants.
        /// </summary>
        internal static string Mandants_Lbl {
            get {
                return ResourceManager.GetString("Mandants_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map_Ttl {
            get {
                return ResourceManager.GetString("Map_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map materials.
        /// </summary>
        internal static string MapMaterials_Ttl {
            get {
                return ResourceManager.GetString("MapMaterials_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message_Lbl {
            get {
                return ResourceManager.GetString("Message_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been successfully sent to Unit Solutions..
        /// </summary>
        internal static string MessageSent_Msg {
            get {
                return ResourceManager.GetString("MessageSent_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent.
        /// </summary>
        internal static string MessageSent_Ttl {
            get {
                return ResourceManager.GetString("MessageSent_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string Meter_Lbl {
            get {
                return ResourceManager.GetString("Meter_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name / Company.
        /// </summary>
        internal static string NameCompany_Lbl {
            get {
                return ResourceManager.GetString("NameCompany_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Name / Company.
        /// </summary>
        internal static string NameCompanyRequired_Msg {
            get {
                return ResourceManager.GetString("NameCompanyRequired_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to.
        /// </summary>
        internal static string NavigateTo_Btn {
            get {
                return ResourceManager.GetString("NavigateTo_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference point found for this location.
        /// </summary>
        internal static string NoBpFound_Msg {
            get {
                return ResourceManager.GetString("NoBpFound_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference point search.
        /// </summary>
        internal static string NoBpFound_Ttl {
            get {
                return ResourceManager.GetString("NoBpFound_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your profile. No form found..
        /// </summary>
        internal static string NoFormFound_Msg {
            get {
                return ResourceManager.GetString("NoFormFound_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string None_Lbl {
            get {
                return ResourceManager.GetString("None_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string North_Lbl {
            get {
                return ResourceManager.GetString("North_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Objects_Ttl {
            get {
                return ResourceManager.GetString("Objects_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objects.
        /// </summary>
        internal static string ObjectsCount_Lbl {
            get {
                return ResourceManager.GetString("ObjectsCount_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects list.
        /// </summary>
        internal static string ObjectsList_Ttl {
            get {
                return ResourceManager.GetString("ObjectsList_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        internal static string ObservationCreationDate {
            get {
                return ResourceManager.GetString("ObservationCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        internal static string Observations_Ttl {
            get {
                return ResourceManager.GetString("Observations_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent on {0:d}.
        /// </summary>
        internal static string ObservationSentDate {
            get {
                return ResourceManager.GetString("ObservationSentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation couldn&apos;t be sent..
        /// </summary>
        internal static string ObservationSentFailed_Msg {
            get {
                return ResourceManager.GetString("ObservationSentFailed_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation has been successfully sent..
        /// </summary>
        internal static string ObservationSentMsg {
            get {
                return ResourceManager.GetString("ObservationSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations list.
        /// </summary>
        internal static string ObservationsList_Ttl {
            get {
                return ResourceManager.GetString("ObservationsList_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of event.
        /// </summary>
        internal static string ObservationTypes_Lbl {
            get {
                return ResourceManager.GetString("ObservationTypes_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems your device is running offline. Please check your Internet connection and retry..
        /// </summary>
        internal static string Offline_Msg {
            get {
                return ResourceManager.GetString("Offline_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok_Btn {
            get {
                return ResourceManager.GetString("Ok_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        internal static string OperationSuccessfull_Toast {
            get {
                return ResourceManager.GetString("OperationSuccessfull_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Optional_Lbl {
            get {
                return ResourceManager.GetString("Optional_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Maps.
        /// </summary>
        internal static string OwnMaps_Ttl {
            get {
                return ResourceManager.GetString("OwnMaps_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber_Lbl {
            get {
                return ResourceManager.GetString("PhoneNumber_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality of photos.
        /// </summary>
        internal static string PhotoQuality_Lbl {
            get {
                return ResourceManager.GetString("PhotoQuality_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string PhotoQualityLarge_Lbl {
            get {
                return ResourceManager.GetString("PhotoQualityLarge_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string PhotoQualityNormal_Lbl {
            get {
                return ResourceManager.GetString("PhotoQualityNormal_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string PhotoQualitySmall_Lbl {
            get {
                return ResourceManager.GetString("PhotoQualitySmall_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from library.
        /// </summary>
        internal static string PickFromGallery_DialBtn {
            get {
                return ResourceManager.GetString("PickFromGallery_DialBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play_Btn {
            get {
                return ResourceManager.GetString("Play_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences_Ttl {
            get {
                return ResourceManager.GetString("Preferences_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register form incomplete.
        /// </summary>
        internal static string RegisterFormIncomplete_Ttl {
            get {
                return ResourceManager.GetString("RegisterFormIncomplete_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationPage_Ttl {
            get {
                return ResourceManager.GetString("RegistrationPage_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required_Lbl {
            get {
                return ResourceManager.GetString("Required_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all data.
        /// </summary>
        internal static string ResetData_Btn {
            get {
                return ResourceManager.GetString("ResetData_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset all data?.
        /// </summary>
        internal static string ResetData_Msg {
            get {
                return ResourceManager.GetString("ResetData_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry_Btn {
            get {
                return ResourceManager.GetString("Retry_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in progress....
        /// </summary>
        internal static string SaveInProgress_Hud {
            get {
                return ResourceManager.GetString("SaveInProgress_Hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop and save record....
        /// </summary>
        internal static string SaveVoiceRecord_Btn {
            get {
                return ResourceManager.GetString("SaveVoiceRecord_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Lbl {
            get {
                return ResourceManager.GetString("Search_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send_Btn {
            get {
                return ResourceManager.GetString("Send_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string SendMessage_Btn {
            get {
                return ResourceManager.GetString("SendMessage_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration request.
        /// </summary>
        internal static string SendRegisterRequest_Btn {
            get {
                return ResourceManager.GetString("SendRegisterRequest_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has been successfully registered..
        /// </summary>
        internal static string SmartPhoneRegisteredMessage {
            get {
                return ResourceManager.GetString("SmartPhoneRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: {0}.
        /// </summary>
        internal static string State_Lbl {
            get {
                return ResourceManager.GetString("State_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop_Btn {
            get {
                return ResourceManager.GetString("Stop_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        internal static string SwitchHybride_Btn {
            get {
                return ResourceManager.GetString("SwitchHybride_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string SwitchPlan_Btn {
            get {
                return ResourceManager.GetString("SwitchPlan_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        internal static string SwitchSatellite_Btn {
            get {
                return ResourceManager.GetString("SwitchSatellite_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to dismiss....
        /// </summary>
        internal static string TabToDismiss_Lbl {
            get {
                return ResourceManager.GetString("TabToDismiss_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        internal static string TakePhoto_DialBtn {
            get {
                return ResourceManager.GetString("TakePhoto_DialBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownDt_Lbl {
            get {
                return ResourceManager.GetString("UnknownDt_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New forms are available on the server. Would you like to update now?.
        /// </summary>
        internal static string UpdateFormRequired_Msg {
            get {
                return ResourceManager.GetString("UpdateFormRequired_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        internal static string UpdateFormRequired_Ttl {
            get {
                return ResourceManager.GetString("UpdateFormRequired_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update informations.
        /// </summary>
        internal static string UpdateInformations_Btn {
            get {
                return ResourceManager.GetString("UpdateInformations_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateNow_Btn {
            get {
                return ResourceManager.GetString("UpdateNow_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check profile....
        /// </summary>
        internal static string UpdateProfile_Btn {
            get {
                return ResourceManager.GetString("UpdateProfile_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload in progress....
        /// </summary>
        internal static string UploadInProgress_Hud {
            get {
                return ResourceManager.GetString("UploadInProgress_Hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is up-to-date..
        /// </summary>
        internal static string UpToDate_Hud {
            get {
                return ResourceManager.GetString("UpToDate_Hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available forms attached to your profile:.
        /// </summary>
        internal static string UserFormsPage_Lbl {
            get {
                return ResourceManager.GetString("UserFormsPage_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string UserImportFormsPage_Ttl {
            get {
                return ResourceManager.GetString("UserImportFormsPage_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your informations has been successfully updated.
        /// </summary>
        internal static string UserInfosUpdated_Msg {
            get {
                return ResourceManager.GetString("UserInfosUpdated_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations updated.
        /// </summary>
        internal static string UserInfosUpdated_Ttl {
            get {
                return ResourceManager.GetString("UserInfosUpdated_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not registered.
        /// </summary>
        internal static string UserNotRegistered {
            get {
                return ResourceManager.GetString("UserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects import.
        /// </summary>
        internal static string UserObjectsImportPage_Ttl {
            get {
                return ResourceManager.GetString("UserObjectsImportPage_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        internal static string UserProfil_Ttl {
            get {
                return ResourceManager.GetString("UserProfil_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are registered.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate location.
        /// </summary>
        internal static string ValidateLocation_Btn {
            get {
                return ResourceManager.GetString("ValidateLocation_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice recorder.
        /// </summary>
        internal static string VoiceRecorder_Ttl {
            get {
                return ResourceManager.GetString("VoiceRecorder_Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Working_Hud {
            get {
                return ResourceManager.GetString("Working_Hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
